namespace RestProcessor
{
    public static class Constants
    {
        public static class AutoGeneratedPage
        {
            public static string TargetFileName = "index.md";
            public static string SummaryFileName = "autogen-overall-summary.md";
            public static string DescriptionMetaName = "service_description";
        }
    }
}
